[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"
  
[[redirects]]
  from = "/alerts/jazzticket/*"
  to = "https://graph-eu01-euwest1.api.smartthings.com/api/token/91150eb1-de4d-45a5-bb5a-77129d5c4f8c/smartapps/installations/327bca3d-4522-474f-a2ee-e84439fde8f5/execute/:34b35ae7c31e8a5fb26bb6a4bf096aa5:"
