backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  identity_url: "https://hambledonfestival.co.uk/.netlify/identity"
  gateway_url: "https://hambledonfestival.co.uk/.netlify/git"
media_folder: static/images
public_folder: images
site_url: https://hambledonfestival.co.uk
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Text", name: "text", widget: "text", required: false}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Text", name: "text", widget: "text", required: false}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image", required: false},
              {label: "Text", name: "text", widget: "text", required: false}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Text", name: "text", widget: "text", required: false}]}